### PR TITLE
Add script to autoformat and CI test to check bibentries

### PR DESCRIPTION
**Pull request by rkaminsk**
Things to consider:
- [x] Check whether the `homogenize_latex_encoding` function does the right thing. Currently, we have a mess of mixed utf-8 and special characters. This function is supposed to fix the issue.
  The function is not usable. The script just replaces unicode symbols now.
- [x] The indentation of the formatted file is different from before. It is probably possible to fine-tune the writer further. But maybe we can also live with it like this?
- [x] What do we do about quotes and braces? In most places I see braces. Maybe just go with braces?
- [x] The default writer lower cases the types of the entries. Just go with it?
- [x] The whole thing has to be tested on real documents.

The `format.py` script requires the [bibtexparser](https://bibtexparser.readthedocs.io/en/master/index.html) module, which can be installed with:
```bash
apt install python3-bibtexparser
# or
pip3 install bibtexparser
```

Running `format.py` results in a `krr_fmt.bib` file. Please have a look at the result. Comments are welcome.

### CODE REVIEW

**Comment by tortinator** [comment]
Thank you, @rkaminsk , for commencing with this!
I see still two issues:
- [ ] abbreviations are expanded and present, what is their purpose?
- [ ] putting braces around uppercase letters at the beginning of words seems arbitrary
Currently, accented characters seem to be described by LaTeX, which is fine

**Comment by rkaminsk** [comment]
> abbreviations are expanded and present, what is their purpose?

I don't know what you mean. Can you give an example?

> putting braces around uppercase letters at the beginning of words seems arbitrary

It is only done for the title field. I don't know why the author of the library did it. I had a look at the source code and it is possible to add a workaround to not do this.

> Currently, accented characters seem to be described by LaTeX, which is fine

This is probably a good idea to be compatible with older systems. But we could also go the other way round and convert everything to unicode.

**Comment by tortinator** [comment]
> > abbreviations are expanded and present, what is their purpose?
> 
> I don't understand the documentation of the project when it comes to this. I think the project is a bit messy here. Will have to look into the source code. The current behavior of the library does not make any sense. I can also try a newer version. Maybe it is a bug that already has a fix.

It is because, for instance, we get both

- @string{springer = {Springer-Verlag}}

-   publisher = {Springer-Verlag},

**Comment by rkaminsk** [comment]
> It is because, for instance, we get both
> 
>  * `@string{springer = {Springer-Verlag}}`
> 
>  * `publisher = {Springer-Verlag}`,

It's a bug in version 1.1 that is fixed in version 1.2. Unfortunately, the homogenize_latex_encoding function does not work with that version anymore. But at least it is not difficult to customize it and use our own. We should probably use the pip version:

```bash
pip install --upgrade bibtexparser
```

I'll push an update later.

**Comment by rkaminsk** [comment]
I fine-tuned the script a bit. Now it only does the substitutions below, which look all fine with me. The file still contains a variety of different ways to output latex special characters. Unfortunately, we cannot use the library to make them uniform because the code in the library is not robust enough.

```
 [-{A}ussagenkalkül},-] {+{A}ussagenkalk{\"u}l},+}
 [-Begründung-] {+Begr{\"u}ndung+}
 [-{Begründungsverwaltung: Beiträge-] {+{Begr{\"u}ndungsverwaltung: Beitr{\"a}ge+}
 [-{Beiträge-] {+{Beitr{\"a}ge+}
 [-Bläsius-] {+Bl{\"a}sius+}
 [-Bögl-] {+B{\"o}gl+}
 [-Böhm-] {+B{\"o}hm+}
 [-Bösel-] {+B{\"o}sel+}
 [-Brüning-] {+Br{\"u}ning+}
 [-Brüning},-] {+Br{\"u}ning},+}
 [-Bücken},-] {+B{\"u}cken},+}
 [-Büning}-] {+B{\"u}ning}+}
 [-Bürckert},-] {+B{\"u}rckert},+}
 [-Crémilleux},-] {+Cr{\'e}milleux},+}
 [-Dempster–Shafer-] {+Dempster\textendash Shafer+}
 [-Diéguez-] {+Di{\'e}guez+}
 [-Ebenhöh-] {+Ebenh{\"o}h+}
 [-Ebenhöh},-] {+Ebenh{\"o}h},+}
 [-Éditions},-] {+{\'E}ditions},+}
 [-einführender {ü}berblick},-] {+einf{\"u}hrender {{\"u}}berblick},+}
 [-{Einführung-] {+{Einf{\"u}hrung+}
 [-{Einführung:-] {+{Einf{\"u}hrung:+}
 [-Einführung-] {+Einf{\"u}hrung+}
 [-Fermüller},-] {+Ferm{\"u}ller},+}
 [-{{FIPA}—towards-] {+{{FIPA}\textemdash towards+}
 [-Fränzle-] {+Fr{\"a}nzle+}
 [-Fröhlich-] {+Fr{\"o}hlich+}
 [-{Fron\-hö\-fer}},-] {+{Fron\-h{\"o}\-fer}},+}
 [-Fronhöfer-] {+Fronh{\"o}fer+}
 [-Fronhöfer},-] {+Fronh{\"o}fer},+}
 [-{Frühjahrsschule Künstliche-] {+{Fr{\"u}hjahrsschule K{\"u}nstliche+}
 [-Frühwirth-] {+Fr{\"u}hwirth+}
 [-Frühwirth},-] {+Fr{\"u}hwirth},+}
 [-für-] {+f{\"u}r+}
 [-Gärdenfors-] {+G{\"a}rdenfors+}
 [-Gärdenfors},-] {+G{\"a}rdenfors},+}
 [-Gödel},-] {+G{\"o}del},+}
 [-Görz-] {+G{\"o}rz+}
 [-Günter-] {+G{\"u}nter+}
 [-Günther-] {+G{\"u}nther+}
 [-Hähnel-] {+H{\"a}hnel+}
 [-Hähnle},-] {+H{\"a}hnle},+}
 [-Hirsimäki},-] {+Hirsim{\"a}ki},+}
 [-Hölldobler-] {+H{\"o}lldobler+}
 [-Hölldobler},-] {+H{\"o}lldobler},+}
 [-Hübner},-] {+H{\"u}bner},+}
 [-Hyvärinen-] {+Hyv{\"a}rinen+}
 [-Hyvärinen},-] {+Hyv{\"a}rinen},+}
 [-Järvisalo-] {+J{\"a}rvisalo+}
 [-Järvisalo},-] {+J{\"a}rvisalo},+}
 [-Jünger},-] {+J{\"u}nger},+}
 [-{Jürgen-] {+{J{\"u}rgen+}
 [-Köhler},-] {+K{\"o}hler},+}
 [-Komplexität-] {+Komplexit{\"a}t+}
 [-König-] {+K{\"o}nig+}
 [-Küchlin},-] {+K{\"u}chlin},+}
 [-{Künstliche-] {+{K{\"u}nstliche+}
 [-Künstliche-] {+K{\"u}nstliche+}
 [-Künstlichen-] {+K{\"u}nstlichen+}
 [-Künzli-] {+K{\"u}nzli+}
 [-Küstlichen-] {+K{\"u}stlichen+}
 [-Langendörfer-] {+Langend{\"o}rfer+}
 [-Lespérance-] {+Lesp{\'e}rance+}
 [-{Linköping-] {+{Link{\"o}ping+}
 [-Linköping-] {+Link{\"o}ping+}
 [-{Logikkalküle},-] {+{Logikkalk{\"u}le},+}
 [-Lühne-] {+L{\"u}hne+}
 [-Möller-] {+M{\"o}ller+}
 [-Mösenlechner-] {+M{\"o}senlechner+}
 [-Müller-] {+M{\"u}ller+}
 [-Müller},-] {+M{\"u}ller},+}
 [-{München,-] {+{M{\"u}nchen,+}
 [-{München},-] {+{M{\"u}nchen},+}
 [-Niemelä-] {+Niemel{\"a}+}
 [-Niemelä},-] {+Niemel{\"a}},+}
 [-Özsoyoglu-] {+{\"O}zsoyoglu+}
 [-özsu},-] {+{\"o}zsu},+}
 [-Paulevé-] {+Paulev{\'e}+}
 [-Pérez-] {+P{\'e}rez+}
 [-{P}rädikatenkalkül},-] {+{P}r{\"a}dikatenkalk{\"u}l},+}
 [-Pührer-] {+P{\"u}hrer+}
 [-Rodríguez-Carbonell},-] {+Rodr{\'\i}guez-Carbonell},+}
 [-Römerhof-] {+R{\"o}merhof+}
 [-Schölkopf-] {+Sch{\"o}lkopf+}
 [-Schöning},-] {+Sch{\"o}ning},+}
 [-Schüller-] {+Sch{\"u}ller+}
 [-Schüller},-] {+Sch{\"u}ller},+}
 [-{Seizième Journées-] {+{Seizi{\`e}me Journ{\'e}es+}
 [-séquentiels-] {+s{\'e}quentiels+}
 [-Sörensson-] {+S{\"o}rensson+}
 [-Sörensson},-] {+S{\"o}rensson},+}
 [-Studienbücher},-] {+Studienb{\"u}cher},+}
 [-Stühmer-] {+St{\"u}hmer+}
 [-Stützle-] {+St{\"u}tzle+}
 [-Stützle},-] {+St{\"u}tzle},+}
 [-Syrjänen},-] {+Syrj{\"a}nen},+}
 [-Türe-] {+T{\"u}re+}
 [-Türe},-] {+T{\"u}re},+}
 [-überblick},-] {+{\"u}berblick},+}
 [-über-] {+{\"u}ber+}
 [-{Über-] {+{{\"U}ber+}
 [-ünel-] {+{\"u}nel+}
 [-Universität München},-] {+Universit{\"a}t M{\"u}nchen},+}
 [-{Universität-] {+{Universit{\"a}t+}
 [-Universität-] {+Universit{\"a}t+}
 [-{Wissensrepräsentation-] {+{Wissensrepr{\"a}sentation+}
 [-Wissensrepräsentation-] {+Wissensrepr{\"a}sentation+}
 [-{Zürich},-] {+{Z{\"u}rich},+}
```

**Comment by tortinator** [comment]
Hi, checking the sorted Version, I just spotted that accented characters are still handled in different ways (which was created manually, I'm afraid):

- author = {P. Cabalar and M. Di\'eguez and F. Laferriere and T. Schaub},
- author = {P. Cabalar and M. Di{\'e}guez and T. Schaub},
- author = {P. Cabalar and M. Di{\'{e}}guez and C. Vidal},

**Comment by rkaminsk** [comment]
> Hi, checking the sorted Version, I just spotted that accented characters are still handled in different ways (which was created manually, I'm afraid):
> 
>     * author = {P. Cabalar and M. Di\'eguez and F. Laferriere and T. Schaub},
> 
>     * author = {P. Cabalar and M. Di{\'e}guez and T. Schaub},
> 
>     * author = {P. Cabalar and M. Di{\'{e}}guez and C. Vidal},

Yes. Unfortunately, I did not find a function to repair this. See my previous comment. The script will replace non-ascii characters with the `{\'e}` version, which we should try to make our default. The script will not touch existing ascii characters.

**Comment by rkaminsk** [comment]
I am done here for now. Additional checks can be implemented in other PRs.

**Comment by rkaminsk** [comment]
There is the [latexcode](https://github.com/mcmtroffaes/latexcodec) package, which we be able to sort out the latex encoding issues. But this is just a note for future improvements and should not stop us from merging this. @tortinator can I merge already?

**Comment by tortinator** [comment]
If you merge now, what would this entail?

**Comment by rkaminsk** [comment]
> If you merge now, what would this entail?

That the bibfile looks differently and that people would have to run the script when adding new entries. The updated bibliography *should just work* in latex projects.

**Comment by tortinator** [comment]
@rkaminsk I fixed the aforementioned issues

**Comment by tortinator** [comment]
What would be now the workflow..?

- PR assumes that check was run/check is run automatically
- what is my role now

**Comment by rkaminsk** [comment]
> What would be now the workflow..?
> 
>     * PR assumes that check was run/check is run automatically
I documented this in the [readme]. In short, people have to run `./bibfmt.py format`.

>     * what is my role now
As before, but you will no longer have to check indentation, formatting, and sorting. You still have to verify that the key is correct and that the entry has the right fields/values.

[readme]: https://github.com/krr-up/bibliography/blob/feature/format/README.md

**Comment by tortinator** [comment]
Sounds good to me! From my perspective, go ahead and merge!
Perhaps we should tag the current state..?

**Review by tortinator — APPROVED** [review]

**Comment by rkaminsk** [comment]
We could add a tag but the relevant commit should also be easy to find in the log. Just search autoformat in the log.

**Pull request merged**
