### PR TITLE
format and order all entries (w emacs/bibtex-mode)

### PR DESCRIPTION
**Pull request by tortinator**
This is to provide a canonical start by ordering and re-formatting both bibfiles;
done with emacs/bibtex-mode

### CODE REVIEW

**Comment by rkaminsk** [comment]
It doesn't look like the bibtex-mode formats entries consistently. Maybe use another tool? We can discuss once Patrick is back.

**Comment by rkaminsk** [comment]
Just as an idea: Could you live with

    biber --tool --output-safechars krr.bib

It cannot be configured to use quotes but always uses braces. There are other things that can be configured though.

**Comment by pluehne** [comment]
@rkaminsk: Will this enforce a consistent ordering of all entries? If we want to provide an autoformatting script and and automation to validate that new entries added via pull requests are in the right format, it would make sense to have a unique ordering.

**Comment by rkaminsk** [comment]
> Will this enforce a consistent ordering of all entries?

By default the entries are sorted by key (regardless of type). But you can configure quite some elaborate sorting schemes with an additional xml config.

This is described in the [manual], which is a bit hard to find. :smile: 

[manual]: https://downloads.sourceforge.net/project/biblatex-biber/biblatex-biber/2.11/documentation/biber.pdf

**Comment by rkaminsk** [comment]
@tortinator:  You can also run

    bibclean krr.bib > /dev/null

which might find additional issues. Even though some can probably be ignored.

**Comment by tortinator** [comment]
@rkaminsk biblean konnte ich jetzt nicht nachinstallieren;
ich merge das jetzt mal und die Tage koennen wir uns ja auf eine
Strategie einschiessen.
Momentan mach ich die Inklusion ja eh' manuall, und so lange kann
ich auch weiter emacs nutzen (auch wenn biber echt geholfen hat!)

**Comment by rkaminsk** [comment]
@tortinator: Sure, the idea with a tool like biber would be that you run it just before committing. When writing an entry, you only have to make sure that it contains all the necessary keys; formatting does not matter.

**Pull request merged**
