### PR TITLE
add page numbers

### PR DESCRIPTION
**Pull request by tortinator**
@cabalar @jorgefandinno @wanko just to let you know that I added pages to the KR20 entry

### CODE REVIEW

**Comment by tortinator** [comment]
@rkaminsk Now it did an explicit check ... mmmh

**Comment by tortinator** [comment]
@rkaminsk Perhaps I just didn't pay attention last time ....

**Comment by rkaminsk** [comment]
It takes a couple of seconds before the test starts and then a couple of minutes to finish. Sometimes the scripts on the page also freeze and you have to reload. At the end it is very visible at the bottom of the PR whether the tests failed or succeeded.

**Comment by rkaminsk** [comment]
And btw. I always click the delete branch button after merging to not have unnecessary branches hanging around.

**Pull request merged**
