### PR TITLE
adding pages to a couple of papers

### PR DESCRIPTION
**Pull request by jorgefandinno**
the bibfmt.py tool also modified a line, though it looks the same to me

### CODE REVIEW

**Comment by rkaminsk** [comment]
@jorgefandinno it just changed the order. Maybe someone checked something in before that was not formatted?

**Review by tortinator — APPROVED** [review]

**Comment by tortinator** [comment]
I'm fine with it, or am I overlooking sth..?

**Review by rkaminsk — APPROVED** [review]
Looks fine.

**Comment by rkaminsk** [comment]
> I'm fine with it, or am I overlooking sth..?

You actually broke it. But since you are an admin, you directly push into the master. :smile:

**Comment by tortinator** [comment]
> > I'm fine with it, or am I overlooking sth..?
> 
> You actually broke it. But since you are an admin, you can directly push into the master.

How can I break anything by making a comment? And what is actually broken..? At a loss @tortinator

**Comment by rkaminsk** [comment]
> > > I'm fine with it, or am I overlooking sth..?
> > 
> > 
> > You actually broke it. But since you are an admin, you can directly push into the master.
> 
> How can I break anything by making a comment? And what is actually broken..? At a loss @tortinator

It was not about a comment but two unchecked commits that are undone by this PR. See a43bdc8954cd479679d1fc1721832ca3ca123f61 and 644f0583599019efb73703b5ef3466ae026d3fff. Anyway, this can be merged and there is no real problem. :wink:

**Pull request merged**
