### PR TITLE
Fix authors

### PR DESCRIPTION
**Pull request by jorgefandinno**
THIS PULL REQUEST IS NOT INTENDED TO BE MERGED!

I have been using a modified version of the ```bibfmt``` program to further automatize the formatting of the BibTeX entries copied from DBLP.
- It abbreviates first names: Roland Kaminski becomes R. Kaminski.
- It generates BibTeX keys from the author names and the year using the bibliography conventions
- It replaces journal names by their corresponding BibTeX strings
- It finds crossrefs in the procs.bib file and uses them for crossref field
- It flags repeated entries

You can try it out by running the following command in the root directory of the repository:
```bash
cp krr-test.bib krr.bib && python bibfmt.py entries && git diff --no-index -w krr-test.bib krr.bib
```
It does not remove repeated entries, it only flags them. They can be removed by running ```python bibfmt.py clean```.
```
python bibfmt.py clean && git diff --no-index -w krr-test.bib krr.bib
```
It keeps the entries in their original order, so you can see them before committing the changes. It does well with most names.
In particular, all the names composed of two words. For names with more than two words the splitting of first/last names is in general ambiguous, so you may need to fix some of them manually: ```Juan Carlos Nieves``` should be parsed as ```Juan Carlos | Nieves``` and ```Manuel Ojeda Aciego``` as ```Manuel | Ojeda Aciego```. 

By default it parses the last two words as part of the last name unless the second is an abbreviation, ```Sheila A. McIlraith``` is parsed as ```Sheila A. | McIlraith```. A list of know exceptions is kept so no need to disambiguate them. It would become crazy the day the King of Spain decides to write a paper about ASP: ```Felipe Juan Pablo Alfonso de Todos los Santos de Borb{\'o}n y Grecia``` should be parsed as ```{Felipe Juan Pablo Alfonso de Todos los Santos} {de Borb{\'o}n y Grecia}```. You should still do ```python bibfmt.py format``` before committing.

Take a look. Maybe we can make it usable for everybody. Somebody may find it useful.

### CODE REVIEW

**Comment by rkaminsk** [comment]
This is way too much code. From a maintenance point of view I would say we cannot merge this. Maybe we should approach this in smaller steps addressing things first that don't need hundreds of lines of code.

**Comment by jorgefandinno** [comment]
@rkaminsk  What do you think about the following plan?
- Keep only the functionality of abbreviating names (I find this the most tedious)
- Make this an independent script, so the previous script is untouched

**Comment by rkaminsk** [comment]
If you could move your code to a separate file and keep the changes to the bibfmt script fairly minimal, then it should be fine.

**Comment by jorgefandinno** [comment]
I separated the script in a new file ```authfmt.py``` which is about 100 lines of code (most of them are small functions so logical code is far less). It only formats author names for now. 

There are 4 lines changes in ```bibfmt.py```.

There is also a new file ```splitnames.py```. This is basically a copy of the function ```split_names()``` from https://bibtexparser.readthedocs.io/en/docs-no-who/_modules/bibtexparser/customization.html#splitname. The modification is small to be used with the format of our bibliography, but since this is  a near 300 line single function the only way to reuse it is to copy it in full and modify it.

Try ```python authfmt.py```.

I removed the code that prevented changes to existing entries. 

Check if the changes introduced are good. In particular, there are two types of changes:
- Authors are sometimes written in one line and sometimes in several. The script always writes them in one line. If multiple lines is desired, we need to establish a rule on when to wrap.
- There are several authors in the bibliography that do not adhere to abbreviation of first name rule. Are these special cases, or just typos that were undetected?

**Comment by rkaminsk** [comment]
Thanks Jorge, I'll try to have a look. But right now I am a bit busy.

**Review by tortinator — APPROVED** [review]
Muchas gracias!

**Comment by rkaminsk** [comment]
@jorgefandinno, just saw your update. I think that in the current form we could merge this. The current state would just have to be merged with the master. I would not prime the `authfmt.py` script yet but encourage users to run it locally for a while. If this runs reliably, we can think of properly adding it to the bibfmt.py script (the current version is a bit hacky). For the initial commit all the authors should be checked to avoid mess up.

**Comment by jorgefandinno** [comment]
@rkaminsk. it sounds good. 

How do you want to proceed with the initial commit?

Do you need me to do something?

**Pull request merged**
