### PR TITLE
Jorge/fix multiword surnames

### LINKED ISSUE #184: Two words surnames do not work well with TPLP format
Currently there are three different ways in which surnames with more than one word are written in the ```kr.bib``` file. See ```Luis Fariñas del cerro in the following entries: 
https://github.com/krr-up/bibliography/blob/c9ff60e1a1786fb63c647a0fc2ea9449e58b4301/krr.bib#L3446
https://github.com/krr-up/bibliography/blob/c9ff60e1a1786fb63c647a0fc2ea9449e58b4301/krr.bib#L2633
https://github.com/krr-up/bibliography/blob/c9ff60e1a1786fb63c647a0fc2ea9449e58b4301/krr.bib#L9736

With the TPLP format, the first produces ``(...  del Cerro ...)`` instead of ``(... Fariñas del Cerro ...)``. This is not a problem with format that use numbers instead of names.

I did not try the third option, but it should work as well.

Now that we have an automatic tool to format names, we could add the functionality to correctly format surnames with more than one word. The options I am aware of are ``L. {Fari{\~{n}}as del Cerro}`` or ``Fari{\~{n}as del Cerro, L.``

Comments?

### PR DESCRIPTION
**Pull request by jorgefandinno**
This closes #184 regarding multi-word last names. It also fixes inconsistencies with the von part in many names.
For instance, both ``` K. von Luck``` and ``` K. {von Luck}``` appeared in ```krr.bib``` and should be written as the former.
Similarly, names with capitalized von parts such as ```D. {Van Nieuwenborgh}``` should be written as ```D. {V}an Nieuwenborgh``` (https://us.mirrors.cicku.me/ctan/info/bibtex/tamethebeast/ttb_en.pdf, page 26).

The conversion can be automatically applied again if needed by the command
```sh
python last_name_format_transition/authfmt_t.py 
```
The folder ```last_name_format_transition``` and its content can be removed after this is merged.

The script ```authfmt.py``` has been updated to produce the new format.

### CODE REVIEW

**Comment by rkaminsk** [comment]
Is this ready to be merged? I looked at the bibfile and it looks okay.

**Comment by rkaminsk** [comment]
> Names that do not follow bibtex rules but are already present in the
> bibliography are parsed correctly. For instance, if `{Manuel Ojeda} Aciego` is
> already present in the bibliography in that format, new entries with `Manuel
> Ojeda Aciego` will be parsed correctly. This means that names that do not
> follow the bibtex rules only need to be protected by braces the first time they
> are introduced in the bibliography.

How do you decide what is the old and new entry?

**Comment by jorgefandinno** [comment]
> > Names that do not follow bibtex rules but are already present in the
> > bibliography are parsed correctly. For instance, if `{Manuel Ojeda} Aciego` is
> > already present in the bibliography in that format, new entries with `Manuel Ojeda Aciego` will be parsed correctly. This means that names that do not
> > follow the bibtex rules only need to be protected by braces the first time they
> > are introduced in the bibliography.

How do you decide what is the old and new entry?

It does not distinguish between old and new entries. Only between names with multi-word last names are otherwise.
If they do not have braces, the bibtex rules force them to have a single word last name. If they have braces or use the comma format, they may have multi-words last names. The idea is that unedited names can be introduced after the first time. For instance, dblp names are provided without braces, and in this way, they need to be edited only once.

It does not have a safe measure if someone decides to introduce a wrongly edited one.

**Comment by tortinator** [comment]
Hi @jorgefandinno and @rkaminsk, thanks for your great efforts! What would be needed as well  is a concise description that we could put into our documentation for the other members in the group.
To be honest, I thought that composed last names are safest written with braces, so that strange bibstyles cannot do harm. Bunow the idea is to loosen this up again..? Sure that (most)  styles can handle that?

**Comment by jorgefandinno** [comment]
> Hi @jorgefandinno and @rkaminsk, thanks for your great efforts! What would be needed as well is a concise description that we could put into our documentation for the other members in the group. To be honest, I thought that composed last names are safest written with braces, so that strange bibstyles cannot do harm. Bunow the idea is to loosen this up again? Sure that (most) styles can handle that?

bibtex distinguish between `von` and `last` part. For instance, `D. {V}an Nieuwenborgh` is parsed as 
```python
first="D." 
von="Van"
last="Nieuwenborgh"
```
while  `D. {Van Nieuwenborgh}` is parsed as
```python
first="D." 
last="Van Nieuwenborgh"
```
My understanding is that entries should be in order according to the `last` part and ignore the `von` part. Anyway, this is up to the `.sty` file to decide.  Both `tplp` and `aaai` styles ignore this rule and produce the same result with both formats. Other styles make take advantage of the first encoding. 

It will also help in the future for producing keys of entries automatically. The key for this entry took `ni` as the two first letters of the surname, not `va`.

**Comment by rkaminsk** [comment]
> To be honest, I thought that composed last names are safest written with braces, so that strange bibstyles cannot do harm. Bunow the idea is to loosen this up again..? Sure that (most) styles can handle that?

I'd follow the recommended way here. My two cents regarding broken bibtex styles: that's for the editor to fix.

**Comment by jorgefandinno** [comment]
> Hi @jorgefandinno and @rkaminsk, thanks for your great efforts! What would be needed as well is a concise description that we could put into our documentation for the other members in the group. To be honest, I thought that composed last names are safest written with braces, so that strange bibstyles cannot do harm. Bunow the idea is to loosen this up again..? Sure that (most) styles can handle that?

@tortinator, I have added a description about the formatting of multi-word surnames and the use of `authfmt` to the README.

**Comment by jorgefandinno** [comment]
> Hi @jorgefandinno and @rkaminsk, thanks for your great efforts! What would be needed as well  is a concise description that we could put into our documentation for the other members in the group.


@tortinator, added a description to the README.

**Comment by tortinator** [comment]
> @tortinator Are we missing something to merge?

All good @jorgefandinno , I am just busy and asked @rkaminsk to care about putting things in place :innocent:

**Comment by rkaminsk** [comment]
Hi @jorgefandinno, I tried to streamline and refactor a bit. If this is okay for you, I would merge.

**Comment by jorgefandinno** [comment]
> Hi @jorgefandinno, I tried to streamline and refactor a bit. If this is okay for you, I would merge.

It looks good to me. 

I would pin the version in the README for:
```sh
pip install bibtexparser
```
because there is a new API incompatible version

**Comment by rkaminsk** [comment]
> > Hi @jorgefandinno, I tried to streamline and refactor a bit. If this is okay for you, I would merge.
> 
> It looks good to me.
> 
> I would pin the version in the README for:
> 
> ```shell
> pip install bibtexparser
> ```
> 
> because there is a new API incompatible version

Seems like we have to upgrade at some point. But let's not do it now.

**Comment by rkaminsk** [comment]
Done. Hope it will work. :crossed_fingers:

**Pull request merged**
